const fs = require('fs');
const path = require('path');

const safeWrite = (filePath, content) => {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content);
};

const components = [
    {
        name: 'SubServiceHero.jsx',
        content: "import React from 'react';\nimport { Link } from 'react-router-dom';\nimport { ChevronRight, ArrowRight } from 'lucide-react';\n\nexport const SubServiceHero = ({ parentTitle, parentRoute, title, eyebrow, description, theme, visual: Visual }) => (\n    <section className=\"relative pt-[120px] pb-20 lg:pt-[160px] lg:pb-32 px-6 lg:px-8 max-w-[1400px] mx-auto grid grid-cols-1 xl:grid-cols-2 gap-16 items-center\">\n        <div className=\"flex flex-col z-10\">\n            <div className=\"flex items-center gap-2 text-sm font-semibold mb-8 text-[#171717]/60 flex-wrap\">\n                <Link to=\"/\" className=\"hover:text-[#171717] transition-colors shrink-0\">Home</Link>\n                <ChevronRight className=\"w-4 h-4 shrink-0\" />\n                <Link to=\"/services\" className=\"hover:text-[#171717] transition-colors shrink-0\">Services</Link>\n                <ChevronRight className=\"w-4 h-4 shrink-0\" />\n                <Link to={parentRoute} className=\"hover:text-[#171717] transition-colors shrink-0 whitespace-nowrap\">{parentTitle}</Link>\n                <ChevronRight className=\"w-4 h-4 shrink-0\" />\n                <span className={theme.accent + \" shrink-0\"}>{eyebrow}</span>\n            </div>\n            <span className={\"text-[13px] font-bold tracking-[0.2em] uppercase mb-6 \" + theme.accent}>{eyebrow}</span>\n            <h1 className=\"text-4xl md:text-5xl lg:text-[64px] font-heading font-extrabold text-[#171717] leading-[1.1] mb-8 tracking-tight\">{title}</h1>\n            <p className=\"text-lg md:text-xl text-[#171717]/70 leading-relaxed mb-10 max-w-xl\">{description}</p>\n            <div className=\"flex flex-wrap flex-col sm:flex-row items-start sm:items-center gap-4\">\n                <Link to=\"/contact\" className=\"bg-[#171717] text-white px-8 py-4 rounded-full font-semibold text-sm hover:bg-black transition-all shadow-lg flex items-center justify-center gap-2 w-full sm:w-auto\">\n                    Start a Project <ArrowRight className=\"w-4 h-4\" />\n                </Link>\n            </div>\n        </div>\n        <div className=\"relative w-full aspect-square md:aspect-video xl:aspect-square flex justify-center xl:justify-end items-center\">\n            <div className={\"absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[120%] h-[120%] rounded-full opacity-20 blur-3xl -z-10 \" + theme.bg}></div>\n            {Visual && <Visual />}\n        </div>\n    </section>\n);"
    },
    {
        name: 'SubServiceOverview.jsx',
        content: "import React from 'react';\nexport const SubServiceOverview = ({ title, content }) => (\n    <section className=\"py-24 bg-white px-6 lg:px-8\">\n        <div className=\"max-w-[1400px] mx-auto grid grid-cols-1 lg:grid-cols-2 gap-16 items-center\">\n            <h2 className=\"text-3xl lg:text-4xl font-heading font-extrabold text-[#171717]\">{title}</h2>\n            <p className=\"text-lg text-[#171717]/70 leading-relaxed\">{content}</p>\n        </div>\n    </section>\n);"
    },
    {
        name: 'SubServiceCapabilities.jsx',
        content: "import React from 'react';\nexport const SubServiceCapabilities = ({ theme, capabilities }) => (\n    <section className=\"py-24 px-6 lg:px-8 bg-[#FAF9F7]\">\n        <div className=\"max-w-[1400px] mx-auto\">\n            <div className=\"mb-16\">\n                <span className={\"text-[13px] font-bold tracking-[0.2em] uppercase mb-4 block \" + theme.accent}>Capabilities</span>\n                <h2 className=\"text-3xl lg:text-4xl font-heading font-extrabold text-[#171717]\">What We Build</h2>\n            </div>\n            <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\">\n                {capabilities.map((cap, i) => (\n                    <div key={i} className=\"bg-white border border-black/5 rounded-2xl p-8 hover:-translate-y-1 hover:shadow-xl hover:shadow-black/5 transition-all duration-300\">\n                        <div className={\"w-12 h-12 rounded-xl mb-6 flex items-center justify-center \" + theme.softBg + \" \" + theme.accent}>\n                            {cap.icon}\n                        </div>\n                        <h3 className=\"text-xl font-bold text-[#171717] mb-3\">{cap.title}</h3>\n                        <p className=\"text-[#171717]/60 leading-relaxed text-sm\">{cap.desc}</p>\n                    </div>\n                ))}\n            </div>\n        </div>\n    </section>\n);"
    },
    {
        name: 'SubServiceTechnology.jsx',
        content: "import React from 'react';\nexport const SubServiceTechnology = ({ technologies, theme }) => (\n    <section className=\"py-24 bg-white px-6 lg:px-8 border-y border-black/5\">\n        <div className=\"max-w-[1400px] mx-auto flex flex-col md:flex-row items-center gap-12\">\n            <div className=\"w-full md:w-1/3 shrink-0\">\n                <h2 className=\"text-3xl font-heading font-extrabold text-[#171717] mb-4\">Technology Stack</h2>\n                <p className=\"text-[#171717]/60\">Powered by the most robust modern frameworks.</p>\n            </div>\n            <div className=\"w-full md:w-2/3 flex flex-wrap gap-3\">\n                {technologies.map((tech, i) => (\n                    <span key={i} className={\"px-5 py-2.5 rounded-full border border-black/10 text-sm font-medium bg-white shadow-sm hover:scale-105 transition-transform cursor-default \" + theme.accent}>\n                        {tech}\n                    </span>\n                ))}\n            </div>\n        </div>\n    </section>\n);"
    },
    {
        name: 'SubServiceProcess.jsx',
        content: "import React from 'react';\nexport const SubServiceProcess = ({ process, theme }) => (\n    <section className=\"py-24 px-6 lg:px-8 bg-white\">\n        <div className=\"max-w-[1400px] mx-auto\">\n            <div className=\"mb-16\">\n                <span className={\"text-[13px] font-bold tracking-[0.2em] uppercase mb-4 block \" + theme.accent}>Workflow</span>\n                <h2 className=\"text-3xl lg:text-4xl font-heading font-extrabold text-[#171717]\">How It Works</h2>\n            </div>\n            <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12\">\n                {process.map((step, i) => (\n                    <div key={i} className=\"relative group\">\n                        <div className={\"w-14 h-14 rounded-full flex items-center justify-center font-bold text-lg mb-6 bg-white border-2 border-black/10 relative z-10 group-hover:scale-110 transition-transform \" + theme.accent}>\n                            {i + 1}\n                        </div>\n                        <h3 className=\"text-xl font-bold text-[#171717] mb-3\">{step.title}</h3>\n                        <p className=\"text-[#171717]/60 text-sm leading-relaxed\">{step.desc}</p>\n                    </div>\n                ))}\n            </div>\n        </div>\n    </section>\n);"
    },
    {
        name: 'RelatedSubServices.jsx',
        content: "import React from 'react';\nimport { Link } from 'react-router-dom';\nimport { ArrowRight } from 'lucide-react';\n\nexport const RelatedSubServices = ({ links, theme }) => (\n    <section className=\"py-24 px-6 lg:px-8 bg-[#FAF9F7] border-t border-black/5\">\n        <div className=\"max-w-[1400px] mx-auto\">\n            <h2 className=\"text-3xl font-heading font-extrabold text-[#171717] mb-12\">Related Services</h2>\n            <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6\">\n                {links.map((link, i) => (\n                    <Link key={i} to={link.href} className=\"group bg-white border border-black/5 rounded-2xl p-6 hover:-translate-y-2 hover:shadow-xl transition-all duration-300 block\">\n                        <h3 className=\"text-lg font-bold text-[#171717] mb-4 group-hover:text-primary transition-colors\">{link.title}</h3>\n                        <div className={\"w-10 h-10 rounded-full flex items-center justify-center border border-black/10 group-hover:border-transparent transition-all \" + theme.bg + \" \" + theme.accent}>\n                            <ArrowRight className=\"w-4 h-4 -rotate-45 group-hover:rotate-0 transition-all\" />\n                        </div>\n                    </Link>\n                ))}\n            </div>\n        </div>\n    </section>\n);"
    },
    {
        name: 'SubServiceCTA.jsx',
        content: "import React from 'react';\nimport { Link } from 'react-router-dom';\nimport { ArrowRight } from 'lucide-react';\nexport const SubServiceCTA = ({ theme }) => (\n    <section className={\"py-32 px-6 lg:px-8 \" + theme.softBg}>\n        <div className=\"max-w-[1000px] mx-auto text-center flex flex-col items-center\">\n            <h2 className=\"text-4xl md:text-5xl font-heading font-extrabold text-[#171717] mb-6\">Have a project in mind?</h2>\n            <p className=\"text-lg md:text-xl text-[#171717]/70 leading-relaxed max-w-2xl mb-12\">\n                Let's build something meaningful. Tell us what you're building and we'll engineer the solution.\n            </p>\n            <div className=\"flex gap-4\">\n                <Link to=\"/contact\" className=\"bg-[#171717] text-white px-10 py-5 rounded-full font-bold text-sm hover:bg-black transition-all shadow-lg flex items-center gap-3\">\n                    Start a Project <ArrowRight className=\"w-5 h-5\" />\n                </Link>\n                <Link to=\"/services\" className=\"bg-white border border-black/10 text-[#171717] px-10 py-5 rounded-full font-bold text-sm hover:border-black/30 transition-all flex items-center gap-3\">\n                    Explore Services <ArrowRight className=\"w-5 h-5\" />\n                </Link>\n            </div>\n        </div>\n    </section>\n);"
    }
];

components.forEach(c => safeWrite(path.join(__dirname, 'src/components/services/subservices', c.name), c.content));

const pages = [
    { route: 'ui-ux-design/ux-research', component: 'UXResearch', dir: 'uiux', title: 'Understand People Before Designing for Them.', e: 'UX Research', desc: 'Deep qualitative and quantitative behavioral research powering human-centered product development.', t: { accent: 'text-purple-600', bg: 'bg-purple-500', softBg: 'bg-purple-50' }, parentRoute: '/services/ui-ux-design', pName: 'UI/UX Design', order: ['Hero', 'Overview', 'Process', 'Technology', 'Related', 'CTA'] },
    { route: 'ui-ux-design/wireframing', component: 'Wireframing', dir: 'uiux', title: 'Turn Ideas Into Clear Product Structures.', e: 'Wireframing', desc: 'Low-fidelity architectural blueprints isolating structural logic from surface visual aesthetics.', t: { accent: 'text-gray-600', bg: 'bg-gray-400', softBg: 'bg-gray-50' }, parentRoute: '/services/ui-ux-design', pName: 'UI/UX Design', order: ['Hero', 'Overview', 'Capabilities', 'Related', 'CTA'] },
    { route: 'ui-ux-design/prototyping', component: 'Prototyping', dir: 'uiux', title: "Experience the Product Before It's Built.", e: 'Prototyping', desc: 'Lightning-fast interactive models validating complex user journeys instantaneously.', t: { accent: 'text-blue-500', bg: 'bg-blue-500', softBg: 'bg-blue-50' }, parentRoute: '/services/ui-ux-design', pName: 'UI/UX Design', order: ['Hero', 'Overview', 'Capabilities', 'Technology', 'Related', 'CTA'] },
    { route: 'ui-ux-design/ui-design', component: 'UIDesign', dir: 'uiux', title: 'Interfaces With Purpose and Personality.', e: 'UI Design', desc: 'High-fidelity, emotionally resonant interfaces balancing massive conversion with profound beauty.', t: { accent: 'text-pink-500', bg: 'bg-pink-400', softBg: 'bg-pink-50' }, parentRoute: '/services/ui-ux-design', pName: 'UI/UX Design', order: ['Hero', 'Overview', 'Process', 'Capabilities', 'Related', 'CTA'] },
    { route: 'ui-ux-design/design-systems', component: 'DesignSystems', dir: 'uiux', title: 'Consistency at Every Digital Touchpoint.', e: 'Design Systems', desc: 'Scalable React-ready tokenized component libraries ensuring infinite consistency for engineering teams.', t: { accent: 'text-emerald-500', bg: 'bg-emerald-400', softBg: 'bg-emerald-50' }, parentRoute: '/services/ui-ux-design', pName: 'UI/UX Design', order: ['Hero', 'Overview', 'Capabilities', 'Technology', 'Related', 'CTA'] },

    { route: 'ecommerce-development/shopify', component: 'Shopify', dir: 'ecommerce', title: 'Shopify Stores Designed to Sell.', e: 'Shopify', desc: 'Custom headless Shopify architectures maximizing absolute theme versatility and lightning checkouts.', t: { accent: 'text-emerald-600', bg: 'bg-emerald-500', softBg: 'bg-emerald-50' }, parentRoute: '/services/ecommerce-development', pName: 'Ecommerce Development', order: ['Hero', 'Overview', 'Capabilities', 'Related', 'CTA'] },
    { route: 'ecommerce-development/woocommerce', component: 'WooCommerce', dir: 'ecommerce', title: 'Flexible Ecommerce on WordPress.', e: 'WooCommerce', desc: 'Deeply customized open-source Woo commerce experiences granting complete data ownership and limitless CMS capabilities.', t: { accent: 'text-purple-600', bg: 'bg-purple-500', softBg: 'bg-purple-50' }, parentRoute: '/services/ecommerce-development', pName: 'Ecommerce Development', order: ['Hero', 'Overview', 'Technology', 'Process', 'Related', 'CTA'] },
    { route: 'ecommerce-development/custom-ecommerce', component: 'CustomEcommerce', dir: 'ecommerce', title: 'Ecommerce Without Platform Limitations.', e: 'Custom Ecommerce', desc: 'Next.js and Node.js bespoke storefronts engineered from scratch for massive unique catalog demands.', t: { accent: 'text-orange-500', bg: 'bg-orange-400', softBg: 'bg-orange-50' }, parentRoute: '/services/ecommerce-development', pName: 'Ecommerce Development', order: ['Hero', 'Overview', 'Capabilities', 'Technology', 'Related', 'CTA'] },
    { route: 'ecommerce-development/payment-integration', component: 'PaymentIntegration', dir: 'ecommerce', title: 'Checkout Experiences Built for Trust.', e: 'Payment Integration', desc: 'Secure, multi-gateway integration ensuring absolute PCI compliance and seamless subscription recurring billing.', t: { accent: 'text-blue-500', bg: 'bg-blue-500', softBg: 'bg-blue-50' }, parentRoute: '/services/ecommerce-development', pName: 'Ecommerce Development', order: ['Hero', 'Overview', 'Process', 'Related', 'CTA'] },
    { route: 'ecommerce-development/marketplace-development', component: 'MarketplaceDev', dir: 'ecommerce', title: 'Digital Marketplaces Built for Multiple Sides.', e: 'Marketplace Development', desc: 'Multi-vendor B2B or B2C platforms orchestrating extreme complexity securely and effortlessly.', t: { accent: 'text-pink-600', bg: 'bg-pink-500', softBg: 'bg-pink-50' }, parentRoute: '/services/ecommerce-development', pName: 'Ecommerce Development', order: ['Hero', 'Overview', 'Capabilities', 'Related', 'CTA'] },

    { route: 'software-development/crm', component: 'CRM', dir: 'software', title: 'Customer Relationships, Better Organized.', e: 'CRM', desc: 'Bespoke pipelines tailored to exactly how your specific sales organization actually operates natively.', t: { accent: 'text-indigo-600', bg: 'bg-indigo-500', softBg: 'bg-indigo-50' }, parentRoute: '/services/software-development', pName: 'Software Development', order: ['Hero', 'Overview', 'Capabilities', 'Related', 'CTA'] },
    { route: 'software-development/erp', component: 'ERP', dir: 'software', title: 'Connect Your Business From One Place.', e: 'ERP', desc: 'Total resource planning software merging finance, inventory, HR, and daily operations onto a single master dashboard.', t: { accent: 'text-yellow-600', bg: 'bg-yellow-500', softBg: 'bg-yellow-50' }, parentRoute: '/services/software-development', pName: 'Software Development', order: ['Hero', 'Overview', 'Technology', 'Process', 'Related', 'CTA'] },
    { route: 'software-development/saas', component: 'SaaS', dir: 'software', title: 'SaaS Products Built to Scale.', e: 'SaaS', desc: 'Multi-tenant cloud architectures constructed natively for massive subscription billing scaling.', t: { accent: 'text-blue-500', bg: 'bg-blue-500', softBg: 'bg-blue-50' }, parentRoute: '/services/software-development', pName: 'Software Development', order: ['Hero', 'Overview', 'Capabilities', 'Technology', 'Related', 'CTA'] },
    { route: 'software-development/business-automation', component: 'BusinessAutomation', dir: 'software', title: 'Replace Repetitive Work With Intelligent Workflows.', e: 'Business Automation', desc: 'Connecting distinct internal platforms programmatically to remove human bottlenecks entirely in realtime.', t: { accent: 'text-pink-600', bg: 'bg-pink-500', softBg: 'bg-pink-50' }, parentRoute: '/services/software-development', pName: 'Software Development', order: ['Hero', 'Overview', 'Process', 'Related', 'CTA'] },
    { route: 'software-development/api-development', component: 'APIDevelopment', dir: 'software', title: 'The Infrastructure Behind Connected Products.', e: 'API Development', desc: 'Bulletproof RESTful and GraphQL backend infrastructures handling incredible concurrency flawlessly.', t: { accent: 'text-emerald-500', bg: 'bg-emerald-500', softBg: 'bg-emerald-50' }, parentRoute: '/services/software-development', pName: 'Software Development', order: ['Hero', 'Overview', 'Capabilities', 'Technology', 'Related', 'CTA'] },

    { route: 'digital-marketing/seo', component: 'SEO', dir: 'marketing', title: 'Get Found by the People Looking for You.', e: 'SEO', desc: 'Extreme technical and semantic on-page optimizations dictating absolute dominance in search landscapes.', t: { accent: 'text-emerald-600', bg: 'bg-emerald-500', softBg: 'bg-emerald-50' }, parentRoute: '/services/digital-marketing', pName: 'Digital Marketing', order: ['Hero', 'Overview', 'Capabilities', 'Process', 'Related', 'CTA'] },
    { route: 'digital-marketing/ppc', component: 'PPC', dir: 'marketing', title: 'Turn Paid Clicks Into Measurable Growth.', e: 'PPC', desc: 'Viciously optimized Google and Meta media buys protecting Return On Ad Spend at all costs natively.', t: { accent: 'text-blue-600', bg: 'bg-blue-500', softBg: 'bg-blue-50' }, parentRoute: '/services/digital-marketing', pName: 'Digital Marketing', order: ['Hero', 'Overview', 'Process', 'Related', 'CTA'] },
    { route: 'digital-marketing/social-media', component: 'SocialMedia', dir: 'marketing', title: 'Build Brands People Want to Follow.', e: 'Social Media', desc: 'Engaging content algorithms and community architecture mapping social identity directly to pipeline revenue.', t: { accent: 'text-pink-500', bg: 'bg-pink-500', softBg: 'bg-pink-50' }, parentRoute: '/services/digital-marketing', pName: 'Digital Marketing', order: ['Hero', 'Overview', 'Capabilities', 'Related', 'CTA'] },
    { route: 'digital-marketing/content-marketing', component: 'ContentMarketing', dir: 'marketing', title: 'Content That Earns Attention and Trust.', e: 'Content Marketing', desc: 'Editorial velocity combined with intent mapping, generating extreme authority and inbound lead captures.', t: { accent: 'text-orange-500', bg: 'bg-orange-500', softBg: 'bg-orange-50' }, parentRoute: '/services/digital-marketing', pName: 'Digital Marketing', order: ['Hero', 'Overview', 'Process', 'Related', 'CTA'] },
    { route: 'digital-marketing/performance-marketing', component: 'PerformanceMarketing', dir: 'marketing', title: 'Every Campaign Should Have a Number Behind It.', e: 'Performance Marketing', desc: 'Complete funnel attribution from first-touch click all the way down to closed Salesforce revenue tracking.', t: { accent: 'text-purple-600', bg: 'bg-purple-500', softBg: 'bg-purple-50' }, parentRoute: '/services/digital-marketing', pName: 'Digital Marketing', order: ['Hero', 'Overview', 'Capabilities', 'Technology', 'Related', 'CTA'] },

    { route: 'mobile-app-development/ios-development', component: 'IOSDevelopment', dir: 'mobile', title: 'Beautiful Experiences for Apple Devices.', e: 'iOS Development', desc: 'Native Swift programming generating 120hz fluid experiences explicitly optimizing Apple architecture.', t: { accent: 'text-blue-500', bg: 'bg-blue-500', softBg: 'bg-blue-50' }, parentRoute: '/services/mobile-app-development', pName: 'Mobile App Development', order: ['Hero', 'Overview', 'Capabilities', 'Technology', 'Related', 'CTA'] },
    { route: 'mobile-app-development/android-development', component: 'AndroidDevelopment', dir: 'mobile', title: 'Android Apps Built for Real-World Scale.', e: 'Android Development', desc: 'Kotlin-based platforms running flawlessly across the massive fragmentation of global Android devices.', t: { accent: 'text-emerald-500', bg: 'bg-emerald-500', softBg: 'bg-emerald-50' }, parentRoute: '/services/mobile-app-development', pName: 'Mobile App Development', order: ['Hero', 'Overview', 'Process', 'Related', 'CTA'] },
    { route: 'mobile-app-development/flutter-development', component: 'FlutterDev', dir: 'mobile', title: 'One Codebase. Beautifully Delivered.', e: 'Flutter', desc: 'High velocity cross platform rendering frameworks delivering native C++ speed simultaneously natively.', t: { accent: 'text-blue-600', bg: 'bg-blue-600', softBg: 'bg-blue-50' }, parentRoute: '/services/mobile-app-development', pName: 'Mobile App Development', order: ['Hero', 'Overview', 'Capabilities', 'Technology', 'Related', 'CTA'] },
    { route: 'mobile-app-development/react-native-development', component: 'ReactNativeDev', dir: 'mobile', title: 'Native Mobile Experiences with a Shared Codebase.', e: 'React Native', desc: 'Leveraging web Javascript infrastructure to generate native device bridges saving 40% engineering time efficiently.', t: { accent: 'text-purple-500', bg: 'bg-purple-500', softBg: 'bg-purple-50' }, parentRoute: '/services/mobile-app-development', pName: 'Mobile App Development', order: ['Hero', 'Overview', 'Process', 'Technology', 'Related', 'CTA'] },
    { route: 'mobile-app-development/cross-platform-apps', component: 'CrossPlatform', dir: 'mobile', title: 'One Product. Multiple Platforms.', e: 'Cross-Platform Apps', desc: 'Omnichannel development frameworks unifying Web, iOS, and Android tightly from a singular repository.', t: { accent: 'text-orange-500', bg: 'bg-orange-500', softBg: 'bg-orange-50' }, parentRoute: '/services/mobile-app-development', pName: 'Mobile App Development', order: ['Hero', 'Overview', 'Capabilities', 'Related', 'CTA'] }
];

pages.forEach(p => {
    const lines = [];
    lines.push("import React from 'react';");
    lines.push("import useSEO from '../../../hooks/useSEO';");
    lines.push("import PageTransition from '../../../components/common/PageTransition';");
    if (p.order.includes('Hero')) lines.push("import { SubServiceHero } from '../../../components/services/subservices/SubServiceHero';");
    if (p.order.includes('Overview')) lines.push("import { SubServiceOverview } from '../../../components/services/subservices/SubServiceOverview';");
    if (p.order.includes('Capabilities')) lines.push("import { SubServiceCapabilities } from '../../../components/services/subservices/SubServiceCapabilities';");
    if (p.order.includes('Technology')) lines.push("import { SubServiceTechnology } from '../../../components/services/subservices/SubServiceTechnology';");
    if (p.order.includes('Process')) lines.push("import { SubServiceProcess } from '../../../components/services/subservices/SubServiceProcess';");
    if (p.order.includes('Related')) lines.push("import { RelatedSubServices } from '../../../components/services/subservices/RelatedSubServices';");
    if (p.order.includes('CTA')) lines.push("import { SubServiceCTA } from '../../../components/services/subservices/SubServiceCTA';");
    lines.push("import { Code, Monitor, Rocket } from 'lucide-react';\n");

    lines.push(`const ${p.component} = () => {`);
    lines.push(`    useSEO({ title: "${p.e} Services | The Digital Connect", description: "${p.desc}" });`);
    lines.push(`    const theme = { accent: "${p.t.accent}", bg: "${p.t.bg}", softBg: "${p.t.softBg}" };\n`);
    lines.push(`    return (\n        <PageTransition>\n            <div className=\"w-full bg-[#FAF9F7] min-h-screen font-sans overflow-hidden\">`);

    if (p.order.includes('Hero')) {
        lines.push(`                <SubServiceHero parentTitle="${p.pName}" parentRoute="${p.parentRoute}" eyebrow="${p.e}" title="${p.title}" description="${p.desc}" theme={theme} />`);
    }
    if (p.order.includes('Overview')) {
        lines.push(`                <SubServiceOverview title="Engineered for performance." content="We don't rely on cookie-cutter solutions or simple drag-and-drop mechanics. Our engineering and marketing teams integrate deeply into your business logic, extracting exactly what makes you unique and mapping it algorithmically to the digital interfaces that generate unquestionable authority." />`);
    }
    if (p.order.includes('Capabilities')) {
        lines.push(`                <SubServiceCapabilities theme={theme} capabilities={[{ title: "Core Architecture", desc: "Constructing the primary robust systems bridging frontend aesthetics to logic.", icon: <Code /> },{ title: "Performance Scaling", desc: "Advanced caching schemas enabling lightning fast interactions globally.", icon: <Rocket /> },{ title: "User Interfaces", desc: "Human centered aesthetics dropping friction entirely.", icon: <Monitor /> }]} />`);
    }
    if (p.order.includes('Technology')) {
        lines.push(`                <SubServiceTechnology theme={theme} technologies={['React', 'Next.js', 'Node.js', 'TypeScript', 'AWS', 'Figma', 'PostgreSQL', 'Tailwind CSS']} />`);
    }
    if (p.order.includes('Process')) {
        lines.push(`                <SubServiceProcess theme={theme} process={[{ title: 'Evaluate', desc: 'Understanding distinct workflows and limits.' },{ title: 'Architect', desc: 'Drafting robust foundational diagrams safely.' },{ title: 'Engineer', desc: 'Creating immaculate, scalable production setups.' },{ title: 'Deploy', desc: 'Zero downtime transition into immediate market utility.' }]} />`);
    }
    if (p.order.includes('Related')) {
        lines.push(`                <RelatedSubServices theme={theme} links={[{ title: 'Backend Engineering', href: '/services/web-development/backend-development' },{ title: 'App Development', href: '/services/mobile-app-development' },{ title: 'Performance Media', href: '/services/digital-marketing/performance-marketing' }]} />`);
    }
    if (p.order.includes('CTA')) {
        lines.push(`                <SubServiceCTA theme={theme} />`);
    }

    lines.push(`            </div>\n        </PageTransition>\n    );\n};\n\nexport default ${p.component};`);

    safeWrite(path.join(__dirname, 'src/pages/services', p.dir, p.component + '.jsx'), lines.join('\n'));
});

// Update the AppRoutes.jsx file safely finding the router declaration
const appRoutesPath = path.join(__dirname, 'src/routes/AppRoutes.jsx');
let appRoutesContent = fs.readFileSync(appRoutesPath, 'utf8');

const importsLines = pages.map(p => `import ${p.component} from '../pages/services/${p.dir}/${p.component}';`).join('\n');
const routesLines = pages.map(p => `<Route path="/services/${p.route}" element={<${p.component} />} />`).join('\n                    ');

appRoutesContent = appRoutesContent.replace('const AppRoutes = () => {', importsLines + '\n\nconst AppRoutes = () => {');
appRoutesContent = appRoutesContent.replace('<Route path="*" element={<NotFound />} />', routesLines + '\n                    <Route path="*" element={<NotFound />} />');

fs.writeFileSync(appRoutesPath, appRoutesContent);
console.log("Successfully generated all subservice pages and components.");
