import React from 'react';
import useSEO from '../../../hooks/useSEO';
import PageTransition from '../../../components/common/PageTransition';
import { SubServiceShared } from '../../../components/services/subservices/SubServiceShared';
import { AndroidVisual } from '../../../components/services/subservices/visuals/VisualsMobile';
import { Database, Rocket, Bell, Cpu, CreditCard, Code, Layers, Smartphone, Wifi, BatteryCharging, PlaySquare, FileCode2, Network, Zap, Sparkles, Boxes, MonitorSmartphone, Box, RefreshCw, Globe, Users, ShieldCheck, Search, LayoutDashboard } from 'lucide-react';


const AndroidDevelopment = () => {
    useSEO({ title: "Universal Reach, Perfectly Engineered. | The Digital Connect", description: "We engineer complex Kotlin applications navigating mass hardware fragmentation to deliver a singular, frictionless experience globally." });
    const theme = {"accent":"text-emerald-500","bg":"bg-emerald-500","softBg":"bg-emerald-50"};
    return (
        <PageTransition>
            <div className="w-full bg-white min-h-screen font-sans">
                <SubServiceShared.Hero parentTitle="Mobile App Development" parentRoute="/services/mobile-app-development" eyebrow="Android Development" title="Universal Reach, Perfectly Engineered." description="We engineer complex Kotlin applications navigating mass hardware fragmentation to deliver a singular, frictionless experience globally." theme={theme} visual={AndroidVisual} />
                <SubServiceShared.Overview title="Built exclusively for the massive Android ecosystem" content={["Android dominates global market share, spread across thousands of distinct device manufacturers, varying screen dimensions, and completely different OS versions. A poor Android team builds an app that breaks on older phones. We engineer robust logic that operates seamlessly across the entire hardware spectrum.","Our primary development backbone relies entirely on Kotlin. By shifting away from legacy Java structures, we construct null-safe, highly concise applications that significantly decrease runtime crashes and drastically speed up development pipelines.","Using Google's Material Design language, we build interfaces that feel deeply native to the platform, capturing immediate trust and ensuring extremely high retention matrices globally."]} theme={theme} />
                <SubServiceShared.Capabilities theme={theme} capabilities={[{title: "Kotlin Coroutines", desc: "Writing asynchronous, non-blocking code executing massive concurrent backend fetches flawlessly.", icon: <Code />}, {title: "Material Design UI", desc: "Crafting interfaces mapping perfectly to Google responsive component frameworks.", icon: <Layers />}, {title: "Hardware Fragmentation QA", desc: "Rigorous remote testing across physical Samsung, Pixel, and OnePlus devices ensuring visual consistency.", icon: <Smartphone />}, {title: "Deep Device Integration", desc: "Connecting directly to Bluetooth LE, internal filesystems, and complex camera APIs securely.", icon: <Wifi />}, {title: "Background Processing", desc: "WorkManager APIs running complex background tasks silently without draining lithium-ion battery reserves.", icon: <BatteryCharging />}, {title: "Play Store Distribution", desc: "Complete deployment, from staged rollouts scaling up to huge A/B testing on live marketplace users.", icon: <PlaySquare />}]} />
                <SubServiceShared.Technology theme={theme} technologies={["Kotlin","Java","Android SDK","Jetpack Compose","Room","Retrofit","Firebase","Play Console"]} />
                <SubServiceShared.Process theme={theme} process={[{"title":"Ecosystem Mapping","desc":"Identifying the target demographic device spectrum to optimize OS version compatibility."},{"title":"Jetpack Compose UI","desc":"Using Google's modern toolkit for building robust native UIs via incredibly rapid declarative methods."},{"title":"API Integration","desc":"Wiring asynchronous Retrofit algorithms fetching live data directly from secure server architectures."},{"title":"Beta & Launch","desc":"Utilizing closed beta tracks to hunt fragmented bugs prior to the immense global production rollout."}]} />
                <SubServiceShared.FAQ theme={theme} faqs={[{"q":"Is Kotlin necessary for modern Android apps?","a":"Yes. Google strictly recommends Kotlin over Java. It profoundly reduces boilerplate code, inherently avoids major crash types (NullPointerExceptions), and integrates flawlessly with modern Jetpack libraries."},{"q":"How do you handle UI across different screens?","a":"Rather than hardcoding sizes, we design utilizing strict constraint layouts and fluid scaling vectors, ensuring identical aesthetics on a large foldable device and a budget 5-inch phone."},{"q":"Can we port an iOS app directly to Android?","a":"Aesthetically? No. Android has distinct navigation archetypes (like floating action buttons) that iOS lacks. We rewrite the UI to feel natively Android, even while the core logic remains philosophically identical."},{"q":"Do you manage Android security?","a":"Absolutely. We enforce SSL pinning, ProGuard code obfuscation natively, and deep encryption for local Room database instances protecting user integrity."}]} />
                <SubServiceShared.Related theme={theme} links={[{"title":"iOS Engineering","href":"/services/mobile-app-development/ios-development"},{"title":"Cross-Platform Apps","href":"/services/mobile-app-development/cross-platform-apps"},{"title":"Backend Software","href":"/services/web-development/backend-development"},{"title":"UI/UX Design","href":"/services/ui-ux-design"}]} />
                <SubServiceShared.CTA theme={theme} />
            </div>
        </PageTransition>
    );
};

export default AndroidDevelopment;
