import React from 'react';
import useSEO from '../../../hooks/useSEO';
import PageTransition from '../../../components/common/PageTransition';
import { SubServiceShared } from '../../../components/services/subservices/SubServiceShared';
import { CrossPlatformVisual } from '../../../components/services/subservices/visuals/VisualsMobile';
import { Database, Rocket, Bell, Cpu, CreditCard, Code, Layers, Smartphone, Wifi, BatteryCharging, PlaySquare, FileCode2, Network, Zap, Sparkles, Boxes, MonitorSmartphone, Box, RefreshCw, Globe, Users, ShieldCheck, Search, LayoutDashboard } from 'lucide-react';


const CrossPlatformApps = () => {
    useSEO({ title: "One Solitary Codebase. Universal Enterprise Output. | The Digital Connect", description: "Simultaneous immense multi-store deployments slicing physical production cycles by half without sacrificing critical application robustness." });
    const theme = {"accent":"text-orange-500","bg":"bg-orange-500","softBg":"bg-orange-50"};
    return (
        <PageTransition>
            <div className="w-full bg-white min-h-screen font-sans">
                <SubServiceShared.Hero parentTitle="Mobile App Development" parentRoute="/services/mobile-app-development" eyebrow="Cross-Platform Apps" title="One Solitary Codebase. Universal Enterprise Output." description="Simultaneous immense multi-store deployments slicing physical production cycles by half without sacrificing critical application robustness." theme={theme} visual={CrossPlatformVisual} />
                <SubServiceShared.Overview title="Eliminate redundant operational engineering" content={["Traditional digital scaling demands three separate engineering teams: one for Web, one for iOS, and one for Android. This triples your physical financial overhead, heavily fractures the product identity, and transforms simple feature updates into massive agonizing synchronization bottlenecks.","Cross-platform development represents the definitive solution for immediate modern enterprise scaling. Utilizing advanced architectures like React Native or Flutter, we author the fundamental business logic literally once. We update, test, and debug that one source of truth exclusively.","Upon compilation, the codebase algorithmically generates highly optimized applications universally across essentially every major device standard globally, drastically shrinking resource expenses while doubling operational shipping velocity immediately."]} theme={theme} />
                <SubServiceShared.Capabilities theme={theme} capabilities={[{title: "Consolidated Engineering", desc: "Removing siloed OS teams converting complex updates into a single singular agile deployment strategy.", icon: <Users />}, {title: "Feature Parity Guaranteed", desc: "Preventing devastating scenarios where Android customers receive updates significantly fundamentally slower than iOS users.", icon: <ShieldCheck />}, {title: "Drastic Expense Reduction", desc: "Saving roughly 40% of the entire macro IT budget by totally negating massive duplicate developmental pipelines permanently.", icon: <CreditCard />}, {title: "Rapid Market Penetration", desc: "Releasing Minimum Viable Products literally twice as quickly drastically increasing crucial early adoption momentum.", icon: <Rocket />}, {title: "Unified Code Auditing", desc: "Centralizing quality assurance processes discovering hidden critical variable vulnerabilities vastly earlier natively.", icon: <Search />}, {title: "Shared Web Expansion", desc: "Seamlessly porting massive mobile logic chunks explicitly outward generating internal administrative React dashboards effortlessly.", icon: <LayoutDashboard />}]} />
                <SubServiceShared.Technology theme={theme} technologies={["React Native","Flutter","TypeScript","Dart","Firebase","Redux","AWS Amplify","Bitrise CI/CD"]} />
                <SubServiceShared.Process theme={theme} process={[{"title":"Framework Evaluation","desc":"Selecting between Flutter (for profound bespoke graphics) or React Native (for immense logic reuse) based on your exact business mechanics."},{"title":"Universal UI Modeling","desc":"Building dynamic Figma components structured explicitly adjusting mathematically based around underlying device bounds."},{"title":"Core Logic Engineering","desc":"Drafting the massive central nervous system connecting natively seamlessly outward towards separate physical hardware abstraction layers."},{"title":"Dual-Pipeline Compilation","desc":"Deploying isolated identical binaries simultaneously directly to both Apple and Google verification matrix servers flawlessly."}]} />
                <SubServiceShared.FAQ theme={theme} faqs={[{"q":"Which cross-platform tool is significantly better?","a":"Neither is objectively \"better.\" If you heavily utilize custom 3D animations or complex branding, Flutter dominates perfectly. If you have an existing massive React-web infrastructure, React Native is vastly superior."},{"q":"Will a cross-platform app drain user batteries?","a":"Historically, legacy tools (Cordova/Ionic) suffered performance drains due to browser abstraction. Modern engines (Flutter/React Native) execute incredibly efficiently, using hardware acceleration fundamentally identical to purely native Swift logic."},{"q":"Do we still need two developer accounts?","a":"Yes. You are still technically submitting uniquely processed packages explicitly via your own Apple Developer Account ($99/yr) and Google Play Console ($25/once) natively."},{"q":"Does cross-platform limit specific OS features?","a":"Rarely. Over 98% of functionality (GPS, Camera, Notifications, Accelerometer) is supported flawlessly. For hyper-bleeding-edge exclusive hardware, we securely write tiny native plugins bypassing the restriction instantly."}]} />
                <SubServiceShared.Related theme={theme} links={[{"title":"Flutter Innovation","href":"/services/mobile-app-development/flutter-development"},{"title":"React Native Apps","href":"/services/mobile-app-development/react-native-development"},{"title":"API Integrations","href":"/services/web-development/api-integration"},{"title":"Mobile UI/UX","href":"/services/ui-ux-design"}]} />
                <SubServiceShared.CTA theme={theme} />
            </div>
        </PageTransition>
    );
};

export default CrossPlatformApps;
