import React from 'react';
import useSEO from '../../../hooks/useSEO';
import PageTransition from '../../../components/common/PageTransition';
import { SubServiceShared } from '../../../components/services/subservices/SubServiceShared';
import { FlutterVisual } from '../../../components/services/subservices/visuals/VisualsMobile';
import { Database, Rocket, Bell, Cpu, CreditCard, Code, Layers, Smartphone, Wifi, BatteryCharging, PlaySquare, FileCode2, Network, Zap, Sparkles, Boxes, MonitorSmartphone, Box, RefreshCw, Globe, Users, ShieldCheck, Search, LayoutDashboard } from 'lucide-react';


const FlutterDevelopment = () => {
    useSEO({ title: "Uncompromised 60fps Canvas Graphics Globally. | The Digital Connect", description: "Google-backed Dart infrastructures painting incredibly fast, fundamentally beautiful applications completely ignoring traditional native restrictions." });
    const theme = {"accent":"text-brand-electric-cyan","bg":"bg-brand-electric-cyan/20","softBg":"bg-brand-periwinkle/20"};
    return (
        <PageTransition>
            <div className="w-full bg-white min-h-screen font-sans">
                <SubServiceShared.Hero parentTitle="Mobile App Development" parentRoute="/services/mobile-app-development" eyebrow="Flutter" title="Uncompromised 60fps Canvas Graphics Globally." description="Google-backed Dart infrastructures painting incredibly fast, fundamentally beautiful applications completely ignoring traditional native restrictions." theme={theme} visual={FlutterVisual} />
                <SubServiceShared.Overview title="The revolutionary multi-platform graphics engine" content={["Unlike traditional cross-platform tools that map code to OS-specific rules, Flutter functions entirely differently. It is a massive, highly optimized graphics engine that literally paints custom pixels directly to the screen frame-by-frame, completely bypassing rigid smartphone limitations.","Because Flutter is essentially its own canvas, applications look mathematically identical down to the microscopic pixel across iOS, Android, and Desktop regardless of what OS version the user holds.","Engineered by Google and powered heavily by Dart, it is specifically designed to render immensely complex animations with absolute 60hz or 120hz fluidity, making it the dominating choice for products requiring highly custom bespoke interfaces disconnected from standard Apple or Google generic aesthetics."]} theme={theme} />
                <SubServiceShared.Capabilities theme={theme} capabilities={[{title: "Absolute UI Consistency", desc: "Overriding OS variations completely resulting in a fundamentally identical user brand experience everywhere natively.", icon: <MonitorSmartphone />}, {title: "Custom Render Engine", desc: "Leveraging Skia or Impeller graphics architectures bypassing OEM bottlenecks dynamically producing hyper-fast frame rendering.", icon: <Cpu />}, {title: "Provider State Architecture", desc: "Handling massive bidirectional localized data caches ensuring the UI never stutters during incredibly intense internet payloads.", icon: <Layers />}, {title: "Massive Widget Library", desc: "Composing applications extremely fast via utilizing exhaustive pre-built customizable micro-components cleanly stacked together.", icon: <Box />}, {title: "Hot Reload Physics", desc: "Speeding development times drastically by injecting new code directly into the running application milliseconds after compiling.", icon: <RefreshCw />}, {title: "Any Screen Deployment", desc: "A single solitary codebase compiling down simultaneously identically out to Mobile, Web Dashboards, Mac, and Windows executables.", icon: <Globe />}]} />
                <SubServiceShared.Technology theme={theme} technologies={["Flutter","Dart","Skia","Impeller","Provider","Bloc","Firebase","Figma"]} />
                <SubServiceShared.Process theme={theme} process={[{"title":"Widget Architectural Mapping","desc":"Breaking intricate aesthetic Figma files into deeply isolated composable widget elements."},{"title":"State Implementation","desc":"Wiring Bloc or Riverpod patterns protecting global internal data variables cleanly from UI disruptions."},{"title":"Graphics Development","desc":"Programmatically coding custom vector animations rendering seamlessly inside the native engine canvas directly."},{"title":"Simultaneous Compilation","desc":"Outputting executable bundles perfectly ready universally across Apple App Store and Google Play Console environments."}]} />
                <SubServiceShared.FAQ theme={theme} faqs={[{"q":"Is Flutter faster than React Native?","a":"Mathematically, yes. Because React Native relies on bridging JavaScript to a native UI component, there is slight communication friction. Flutter bypasses the native UI completely and draws its own pixels, resulting in incredibly smooth custom animations."},{"q":"Why do so many startups choose Flutter?","a":"Unparalleled development speed. The 'Hot Reload' feature allows engineers to view changes instantly without rebuilding the app. Combined with an identical UI across devices, it drastically reduces time-to-market."},{"q":"Does Flutter create large app sizes?","a":"Because it ships with its entire graphics engine (Skia/Impeller) inside the application package natively, Flutter apps initially have a slightly larger core footprint than purely native frameworks, but usually negligibly so."},{"q":"Can Flutter interact with my camera or GPS?","a":"Absolutely. There is a massive ecosystem of well-maintained plugins granting deep, unthrottled access connecting directly into complex internal hardware peripherals universally."}]} />
                <SubServiceShared.Related theme={theme} links={[{"title":"Cross Platform Development","href":"/services/mobile-app-development/cross-platform-apps"},{"title":"UI/UX Interactive Design","href":"/services/ui-ux-design"},{"title":"React Native Apps","href":"/services/mobile-app-development/react-native-development"},{"title":"Custom Web Applications","href":"/services/web-development/custom-web-applications"}]} />
                <SubServiceShared.CTA theme={theme} />
            </div>
        </PageTransition>
    );
};

export default FlutterDevelopment;
