import React from 'react';
import useSEO from '../../../hooks/useSEO';
import PageTransition from '../../../components/common/PageTransition';
import { SubServiceShared } from '../../../components/services/subservices/SubServiceShared';
import { ReactNativeVisual } from '../../../components/services/subservices/visuals/VisualsMobile';
import { Database, Rocket, Bell, Cpu, CreditCard, Code, Layers, Smartphone, Wifi, BatteryCharging, PlaySquare, FileCode2, Network, Zap, Sparkles, Boxes, MonitorSmartphone, Box, RefreshCw, Globe, Users, ShieldCheck, Search, LayoutDashboard } from 'lucide-react';


const ReactNativeDev = () => {
    useSEO({ title: "Web Talent Intersecting Native Power. | The Digital Connect", description: "Simultaneous iOS and Android deployments using a unified JavaScript pipeline cutting total cost and time dynamically." });
    const theme = {"accent":"text-cyan-500","bg":"bg-cyan-500","softBg":"bg-cyan-50"};
    return (
        <PageTransition>
            <div className="w-full bg-white min-h-screen font-sans">
                <SubServiceShared.Hero parentTitle="Mobile App Development" parentRoute="/services/mobile-app-development" eyebrow="React Native" title="Web Talent Intersecting Native Power." description="Simultaneous iOS and Android deployments using a unified JavaScript pipeline cutting total cost and time dynamically." theme={theme} visual={ReactNativeVisual} />
                <SubServiceShared.Overview title="The premier framework for massive dual-platform deployment" content={["Building two completely separated apps simultaneously in Swift (iOS) and Kotlin (Android) is incredibly robust, but immensely expensive and time-consuming. React Native fundamentally alters that paradigm.","Backed globally by Meta, React Native utilizes a shared JavaScript codebase that translates perfectly into native operating system components. Rather than rendering a slow HTML wrapper, it invokes real native views directly, providing almost imperceptible performance differences from purely native applications.","This enables startups and aggressive enterprises to deploy complex, identical logic across both huge platforms flawlessly while entirely avoiding the nightmare of synchronizing two disconnected engineering departments."]} theme={theme} />
                <SubServiceShared.Capabilities theme={theme} capabilities={[{title: "Shared Codebase", desc: "Writing core logic processing once and compiling natively out to both massive global stores.", icon: <FileCode2 />}, {title: "Native Bridging", desc: "Developing custom C++ or Java bridges when highly specific low-level hardware access is explicitly required.", icon: <Network />}, {title: "Instant OTA Updates", desc: "Bypassing strict App Store review delays by pushing critical Javascript logic directly over-the-air.", icon: <Zap />}, {title: "Redux State Management", desc: "Handling incredible algorithmic states identically aligned flawlessly across both distinct OS environments.", icon: <Layers />}, {title: "Complex Animations", desc: "Employing Reanimated engines running interactions on the native thread guaranteeing 60fps drops zero frames.", icon: <Sparkles />}, {title: "Shared Web Components", desc: "Extracting hooks and abstracting UX elements out for reuse natively inside the React Web browser product.", icon: <Boxes />}]} />
                <SubServiceShared.Technology theme={theme} technologies={["React Native","TypeScript","Expo","Redux","Reanimated","Fastlane","Hermes Engine","Jest"]} />
                <SubServiceShared.Process theme={theme} process={[{"title":"Architecture Unification","desc":"Drafting strict TypeScript structures determining what logic is shared globally and what requires distinct native OS handling."},{"title":"Component Engineering","desc":"Building dynamic interfaces natively leveraging Flexbox layouts ensuring identical ratios on both iPhone and pixel devices."},{"title":"Native Optimization","desc":"Enabling the Hermes engine, slashing RAM overhead immensely, and shrinking initial application boot times dynamically."},{"title":"Automated CI/CD","desc":"Using Fastlane pipelines triggering instantaneous dual-deployments out directly to TestFlight and Google Play Consoles."}]} />
                <SubServiceShared.FAQ theme={theme} faqs={[{"q":"Is React Native just a web view inside an app?","a":"Not at all. Frameworks like Cordova use WebViews (rendering HTML/CSS, which is slow). React Native literally translates your Javascript directly into native OS C++ components. It feels like a real app because it IS a real app."},{"q":"Will the app look identical on iOS and Android?","a":"Mostly yes, but logically no. Good React Native apps adopt native paradigms. A tab-bar or switch component will look like an Apple switch on iOS, and a Material switch on Android automatically based on OS flags."},{"q":"What happens if we need a feature React Native doesn't support?","a":"React Native has an escape hatch. We simply write the missing functionality natively in Swift/Kotlin and bridge it back to the JavaScript main thread."},{"q":"Does React Native save money?","a":"Yes. Because 80% to 95% of the codebase is shared, you only pay for one engineering team instead of completely siloed iOS and Android departments doing redundant logic work."}]} />
                <SubServiceShared.Related theme={theme} links={[{"title":"Cross Platform Apps","href":"/services/mobile-app-development/cross-platform-apps"},{"title":"Frontend React","href":"/services/web-development/frontend-development"},{"title":"Flutter Apps","href":"/services/mobile-app-development/flutter-development"},{"title":"UI/UX Design","href":"/services/ui-ux-design"}]} />
                <SubServiceShared.CTA theme={theme} />
            </div>
        </PageTransition>
    );
};

export default ReactNativeDev;
