import React from 'react';
import useSEO from '../../../hooks/useSEO';
import PageTransition from '../../../components/common/PageTransition';
import { SubServiceShared } from '../../../components/services/subservices/SubServiceShared';
import { FrontendVisual } from '../../../components/services/subservices/visuals/VisualsWeb';
import { PenTool, Database, Zap, Sparkles, Eye, Cloud, Lock, Layers, Webhook, Box, Server, Boxes, GitMerge, LayoutTemplate, ArrowRightLeft, Globe, Languages, Network, RadioReceiver, ShieldCheck, LayoutDashboard, Users, Repeat, Radio, LineChart } from 'lucide-react';


const FrontendDevelopment = () => {
    useSEO({ title: "From Design System to Pixel-Perfect Interface | The Digital Connect", description: "We engineer lightning-fast, accessible, and deeply interactive interfaces that convert casual browsers into dedicated customers. Our frontend architectures are built to scale globally." });
    const theme = {"accent":"text-brand-cyan","bg":"bg-brand-cyan/20","softBg":"bg-brand-soft-blue/20"};
    return (
        <PageTransition>
            <div className="w-full bg-white min-h-screen font-sans">
                <SubServiceShared.Hero parentTitle="Web Development" parentRoute="/services/web-development" eyebrow="Frontend Development" title="From Design System to Pixel-Perfect Interface" description="We engineer lightning-fast, accessible, and deeply interactive interfaces that convert casual browsers into dedicated customers. Our frontend architectures are built to scale globally." theme={theme} visual={FrontendVisual} />
                <SubServiceShared.Overview title="Interfaces Designed for Conversion" content={["The frontend of your application is the definitive touchpoint where users decide whether to trust your brand. We do not just build websites; we engineering digital experiences utilizing cutting-edge component libraries, complex state management, and strict accessibility standards.","Our approach maps perfectly to modern demands. We leverage React and Next.js to provide Server-Side Rendering (SSR) and Static Site Generation (SSG), ensuring lightning-fast load times that dominate Core Web Vitals. Every interaction, hover state, and transition is meticulously coded to feel native, fluid, and intuitive.","Beyond aesthetics, our architectures are strictly modular. By isolating logic into reusable headless components, your marketing and development teams can scale out hundreds of new pages instantly without relying on continuous engineering intervention."]} theme={theme} />
                <SubServiceShared.Capabilities theme={theme} capabilities={[{title: "React & Next.js Architecture", desc: "Constructing massive enterprise-scale component libraries utilizing Next.js App Router for extreme performance.", icon: <Code />}, {title: "Design System Translation", desc: "Pixel-perfect translation of complex Figma design tokens into strict Tailwind configurations.", icon: <PenTool />}, {title: "State Management", desc: "Redux, Zustand, and React Query orchestrating massive real-time data payloads flawlessly.", icon: <Database />}, {title: "Performance Optimization", desc: "Aggressive bundle splitting, layout shift prevention, and sub-second Time To Interactive (TTI).", icon: <Zap />}, {title: "Micro-Animations", desc: "Framer Motion physics-based interactions driving deep user delight and conversion flow.", icon: <Sparkles />}, {title: "Strict Accessibility", desc: "WCAG 2.1 AA compliance natively built into the HTML DOM for universal screen-reader access.", icon: <Eye />}]} />
                <SubServiceShared.Technology theme={theme} technologies={["React","Next.js","TypeScript","Tailwind CSS","Framer Motion","Zustand","React Query","Vite","Storybook","Vercel"]} />
                <SubServiceShared.Process theme={theme} process={[{"title":"Component Auditing","desc":"Analyzing existing design files and breaking them down into reusable, isolated logic tokens."},{"title":"Architecture Setup","desc":"Defining strict Typescript interfaces and state management stores before rendering pixels."},{"title":"Feature Development","desc":"Engineering individual routes, maintaining absolute 100% lighthouse performance scores."},{"title":"QA & Accessibility","desc":"Rigorous cross-device testing across complex viewport breakpoints and edge cases."}]} />
                <SubServiceShared.FAQ theme={theme} faqs={[{"q":"What frontend framework do you primarily use?","a":"We predominantly engineer utilizing React and Next.js, as they provide the most robust enterprise scalability, vibrant ecosystem, and absolute best performance capabilities in modern web development."},{"q":"How do you ensure the website is fast?","a":"We utilize Edge caching, Server-Side Rendering (SSR), aggressive image optimization, code-splitting, and strict Core Web Vitals monitoring during the CI/CD pipeline."},{"q":"Can you implement our existing Figma designs?","a":"Absolutely. We specialize in pixel-perfect translation. We extract your design tokens (colors, typography, spacing) and build a native frontend design system matching it flawlessly."},{"q":"Do you build accessible (WCAG) websites?","a":"Yes. Accessibility is absolutely mandatory. We ensure keyboard navigation, aria-labels, high contrast ratios, and screen-reader compatibility natively."}]} />
                <SubServiceShared.Related theme={theme} links={[{"title":"Backend Development","href":"/services/web-development/backend-development"},{"title":"UI/UX Design","href":"/services/ui-ux-design"},{"title":"SEO Optimization","href":"/services/digital-marketing/seo"},{"title":"Mobile App Development","href":"/services/mobile-app-development"}]} />
                <SubServiceShared.CTA theme={theme} />
            </div>
        </PageTransition>
    );
};

export default FrontendDevelopment;
